### ISSUE TITLE
Add horovod based distributed TF template

### ISSUE THREAD

**Issue by scttl** [IntelAI/mlt#112]
Not entirely sure of the feasibility of this, but general performance gains and reduced complexity of ring based updates (no more central parameter server to specify in scripts) would make for a useful addition to our suite of templates.

The [Horovod](https://github.com/uber/horovod) project already includes a reference [Docker](https://github.com/uber/horovod/blob/master/docs/docker.md) file which might be worth leveraging too.

**Comment by chinnikrishna2231** [comment]
I am working on this, will update here once I have it

**Comment by dmsuehir** [comment]
We got the horovod example from @chinnikrishna2231.  @karthikvadla is picking it up from here to enable running it kubernetes and adding it as a template to MLT.
