### ISSUE TITLE
Validate yaml templates

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#145]
When we get a template submitted to us, we should make sure it's a valid template. See what kube-controllers-go did here: https://github.com/NervanaSystems/kube-controllers-python/blob/master/crdlib/custom_resource_definition.py#L75

Also here is a good example:
https://stackoverflow.com/questions/3262569/validating-a-yaml-document-in-python

**Comment by dmsuehir** [comment]
Add a check to `mlt build` or `mlt deploy` that verifies that the yaml is valid.  (similar to the lint check)

Can also be run as part of our tests to ensure that the yaml files in the templates don't get messed up.
