### ISSUE TITLE
Add support for template versioning

### ISSUE THREAD

**Issue by jitendra42** [IntelAI/mlt#156]
Currently MLT templates do not have version. Add support for versioning MLT container templates. This will enable us to continue enhancing templates as well as smoothly updating template to new version.

For more details please see proposal: https://github.com/NervanaSystems/dls-features/blob/master/proposals/container_templates/README.md

**Comment by dmsuehir** [comment]
This is no longer needed.

**Comment by jitendra42** [comment]
Initially versioning was added for `mlt template update` command to identify the difference. We decided to use git sha to difference the template differentiation. hence template versioning is no longer needed for now.
