### ISSUE TITLE
set initial template version to existing templates

### ISSUE THREAD

**Issue by jitendra42** [IntelAI/mlt#157]
Currently MLT templates do not have any version. Once issue #156 adds support for template versioning, set initial template version to existing templates. 

For more details please see proposal: https://github.com/NervanaSystems/dls-features/blob/master/proposals/container_templates/README.md

**Comment by dmsuehir** [comment]
This is no longer needed.

**Comment by jitendra42** [comment]
Initially versioning was added for `mlt template update` command to identify the difference. We decided to use git sha to difference the template differentiation. hence template versioning is no longer needed for now.
