### ISSUE TITLE
Add `watch` option for `mlt`

### ISSUE THREAD

**Issue by ashahba** [IntelAI/mlt#158]
Add a generic `watch` option for `mlt`.
This will be called after `deploy` is called to watch for code changes in the `app` directory.

This may end up having a bit of overlap with #155 and in fact that PR should only be worked on after this one is done.
The idea is to have the following flow with `mlt`:
```
init
build
deploy
watch
```
Once `watch` is called against an app,  it is being watched for code changes, however the code changes would not trigger Container rebuilds.
This could be done even after the app has been deployed.

See details in dls-feature:
https://github.com/NervanaSystems/dls-features/tree/master/proposals/job_iterations

**Comment by s1113950** [comment]
How is this different from #155 ? Can we close #155 then or is #155 a subtask of this one? if so, can we make that clear somehow?

**Comment by ashahba** [comment]
This is resolved now by #308
