### ISSUE TITLE
Add features.md for feature tracking

### ISSUE THREAD

**Issue by nqn** [IntelAI/mlt#173]
In order to validate each feature against a user and track it's usefulness and maturity, we would like to have an overview of all features we have built or are planning to build

**Comment by dmsuehir** [comment]
Some of these are in the `Projects`. 
https://github.com/IntelAI/mlt/projects

**Comment by ConnorDoyle** [comment]
Using projects is good for tracking work towards a goal, but a doc in the repo has the advantage that changes to it go through the review process. Maybe we could do both.
