### ISSUE TITLE
Update README file to mention pip install

### ISSUE THREAD

**Issue by dmsuehir** [IntelAI/mlt#180]
Add note on the README about pip installing mlt.  Right now, it just says to use `make`. 

* TBD

**Comment by dmsuehir** [comment]
#26

**Comment by dmsuehir** [comment]
I updated the documentation to use `pip install .` for a local pip install, but the doc will need to be updated again after mlt is in the pypi repo.

**Comment by ashahba** [comment]
A PR to document `PyPi` related docs in on the way before we can close this one.
