### ISSUE TITLE
unit tests should test units

### ISSUE THREAD

**Issue by megawidget** [IntelAI/mlt#202]
```
tests/unit/commands/test_templates.py::test_template_list[git@github.com:IntelAI/mlt.git] Enter passphrase for key '/Users/ikaploun/.ssh/id_rsa': 
PASSED
```

😑

**Comment by s1113950** [comment]
@megawidget take a look at this: https://github.com/IntelAI/mlt/pull/349 think I fixed all of that. That one test took like 11 seconds before because we didn't mock much... now the whole suite takes < 6 seconds

**Comment by s1113950** [comment]
This has been done, closing
