### ISSUE TITLE
mlt build has errors

### ISSUE THREAD

**Issue by kkasravi** [IntelAI/mlt#215]
steps to reproduce

1. `pip install mlt`
1. `mlt init --template=hello-world mlt-hello-world`
1. `cd mlt-hello-world`
1. `make build`
>docker build --build-arg HTTP_PROXY= --build-arg HTTPS_PROXY= --build-arg http_proxy= --build-arg https_proxy= -t  .
invalid argument "." for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [build] Error 125

Looks like it is expecting an env var CONTAINER_NAME to be defined

**Comment by dmsuehir** [comment]
@kkasravi  The intended flow is to use `mlt build` at step 4 (not `make build`).
