### ISSUE TITLE
 provide best known method for including private git repositories inside of container

### ISSUE THREAD

**Issue by zach-nervana** [IntelAI/mlt#27]

**Comment by dmsuehir** [comment]
@ashahba  This might be covered by the ksync work?

**Comment by ashahba** [comment]
With `mlt sync` powered by `ksync` being in now, users should be just able to clone any repo to their local directory and have `ksync` take care of uploading it to the container.
This way we no longer need to pass user keys around or even having `git` or other libraries installed in the container.

**Comment by s1113950** [comment]
Can we close this ticket then @zach-nervana @ashahba ?

**Comment by ashahba** [comment]
I personally think yes, since we can achieve this either through `mlt` apps that have `sync` capability or `ksync` itself.
Regardless it's not an issue anymore.
