### ISSUE TITLE
Change default number of re-tries to 120 seconds

### ISSUE THREAD

**Issue by tonyreina** [IntelAI/mlt#270]
Could `mlt logs` have the default number of retries set to 100 seconds? This won't affect small jobs but will help larger ones.

Also, could the "retrying" printout overwrite itself? No need for a separate line for each retry.

Thanks!

**Comment by s1113950** [comment]
This could also be applied to the retries used to wait for pods to spin up in mlt interactive mode!

**Comment by karthikvadla** [comment]
Yeah, Let me add that too.

**Comment by dmsuehir** [comment]
I'm closing this issue, since Karthik's PR fixing this has been merged (it changes the maximum number of retries for both logging and interactive to 120 seconds).
