### ISSUE TITLE
Make mlt deploy keep track of multiple jobs

### ISSUE THREAD

**Issue by tyler-nervana** [IntelAI/mlt#318]
It's really common to want to run multiple training jobs at once in parallel. These may be related and fall under a single experiment, or they may span multiple experiments. `mlt` should be able to track any number of deployments.

I would propose creating subdirectories under the `k8s` directory that hold each deployment. `mlt` can still default to the most recent.

**Comment by dmsuehir** [comment]
dls-feature for this issue has been filed here: https://github.com/NervanaSystems/dls-features/issues/146
