### ISSUE TITLE
Intermittent failure with `test_deploy_check_logs` e2e test

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#410]
See https://circleci.com/gh/IntelAI/mlt/2101?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

If you rerun things pass

Failure happens maybe 1/10 runs.
I wonder if adjusting the waiting times will fix things, or there is another race case in play here

**Comment by s1113950** [comment]
https://circleci.com/gh/IntelAI/mlt/2107?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link too

**Comment by dmsuehir** [comment]
It's possible that maybe we're just missing seeing the logs.  `mlt deploy -l` polls waiting for the pods to start `Running`, but the hello world template completes pretty quickly, so we might be missing seeing `Running` if the pods have already gone to completed.  And, I think `kubetail` does not work once the pods are completed.  I'll try to do some debugging to see if this is the case.
