### ISSUE TITLE
Unable to undeploy horovod

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#422]
Related to comment here: https://github.com/IntelAI/mlt/issues/361#issuecomment-417475946

Hit this with both `--all` and `--job-name` flag

**Comment by s1113950** [comment]
@dmsuehir was unable to repro; it's something with my branch (when I filed this I thought I was on latest `master` *facepalm* ). Will make sure to fix in my branch

**Comment by dmsuehir** [comment]
@s1113950 Should we close this issue since it only exists in your branch and you fixed it on your branch?  😄

**Comment by s1113950** [comment]
When https://github.com/IntelAI/mlt/pull/411 goes in this will be closed 😄 it's set to close it at the top
