### ISSUE TITLE
mlt deploy fails with error but job folder creates in k8s dir

### ISSUE THREAD

**Issue by sudeshsh** [IntelAI/mlt#434]
If the job fails while doing mlt deploy the folder is still created for it in k8s 
This fails mlt undeploy --all as its trying to delete jobs which never got created.

The job failed coz of version discrepancies  in the TFJob

* Need to verify if job creating was successful before create its entry in the k8s folder

**Comment by WafaaT** [comment]
The job sub-dir was created in `k8s` but failed in the `kubectl create -f ` step. I think not only the versioning should be fixed but also we should catch such error in `deploy.py` a `try` `catch` inside this method https://github.com/IntelAI/mlt/blob/bdb86dd64c674c0aa45c9fc8c0def4469921fcc8/mlt/commands/deploy.py#L249 to prevent creating a sub- dir to non deployed job.
